(compiler-semantic-request
           (schema . compiler-semantic-input/1)
           (fixture-id . "car-nested-pair")
           (identity . ((domain . D3) (bits . 100)))
           (law . ((authority-ref . "knowledge/bija3-l1-l5-structure-projection.json")
                   (proof-ref . "contracts/bija3-l1-l5-ratification.lisp")
                   (semantic-status . current)))
           (mechanism . ((execution-role . selector-head)
                         (mechanism-status . unknown)
                         (mechanism-ref . ())))
           (provenance . ((repository . "juv4uk/sens")
                          (revision . "c3878ef2be03894a46bde8263f75138adf276798")
                          (authority-path . "knowledge/bija3-l1-l5-structure-projection.json")
                          (authority-sha256 . "a4d914073bc1a26f3721d404ac74894b99fe057159da76346ad2092a771bdfc9")
                          (contract . 11.6))))
