#!/usr/bin/env python3
"""Consume a real SENS-owned compiler-semantic request.

The positive request is always generated by the pinned SENS producer. This
test never treats a hand-written semantic request as canonical evidence.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SENS_ROOT = ROOT / "vendor" / "sens"
FIXTURE = "car-nested-pair"
VALID = ROOT / "tests" / "compiler_backend_v1.json"
TOOL = ROOT / "host" / "compiler_backend_v1.py"
EXPECTED_COMMIT = "f2e7797283c8dfc2aa67935a02b3735a8290041f"


def cargo_command() -> str:
    resolved = shutil.which("cargo")
    if resolved is not None:
        return resolved
    fallback = Path.home() / ".cargo" / "bin" / "cargo"
    if fallback.is_file():
        return str(fallback)
    raise AssertionError(
        "cargo is required for the pinned SENS producer but is not available "
        "on PATH or at ~/.cargo/bin/cargo"
    )


def produce_sens_request() -> str:
    cargo_toml = SENS_ROOT / "Cargo.toml"
    if not cargo_toml.is_file():
        raise AssertionError(
            f"pinned SENS checkout is missing: {cargo_toml}; run make sens-fetch first"
        )
    result = subprocess.run(
        [
            cargo_command(),
            "run",
            "--quiet",
            "-p",
            "xtask",
            "--",
            "compiler-export",
            "--fixture",
            FIXTURE,
        ],
        cwd=SENS_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise AssertionError(
            "pinned SENS compiler-export failed:\n"
            + result.stdout
            + result.stderr
        )
    generated = result.stdout.strip()
    if not generated.startswith("(compiler-semantic-request"):
        raise AssertionError(
            "pinned SENS compiler-export did not produce a canonical request"
        )
    return generated


def run_sens(path: Path, *extra: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(TOOL),
            "--sens-request",
            str(path),
            *extra,
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def main() -> int:
    generated = produce_sens_request()
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "generated.lisp"
        path.write_text(generated + "\n", encoding="utf-8")

        good = run_sens(
            path,
            "--lower",
            "--gpu-mechanism",
            "futhark.structural.selector-head-v1",
        )
        if good.returncode != 0:
            print(good.stdout + good.stderr)
            return 1

        lowered = json.loads(good.stdout)
        assert lowered["entry"] == "lower_selector_head"
        assert lowered["target"] == "futhark"
        assert lowered["role"] == "SelectorHead"
        assert lowered["source_commit"] == EXPECTED_COMMIT
        assert lowered["fixture_id"] == FIXTURE

        manual = json.loads(VALID.read_text(encoding="utf-8"))
        assert manual["role"] == lowered["role"], (
            "canonical SENS role must match parity fixture"
        )
        assert manual["provenance"]["source_commit"] == lowered["source_commit"]
        assert manual["provenance"]["role_authority_digest"] == lowered[
            "role_authority_digest"
        ]

        stale = generated.replace(EXPECTED_COMMIT, "0" * 40)
        path.write_text(stale + "\n", encoding="utf-8")
        result = run_sens(path)
        assert result.returncode == 2
        assert "stale SENS source revision" in result.stdout

        stale_authority = generated.replace(
            "9768f683e90cfb56ca95675d1f6ac0e6ede91e21cebe97e20b455cf1b3094791",
            "0" * 64,
        )
        path.write_text(stale_authority + "\n", encoding="utf-8")
        result = run_sens(path)
        assert result.returncode == 2
        assert "stale SENS role authority digest" in result.stdout

        d8 = generated.replace(
            "(domain . D3) (bits . 100)", "(domain . D8) (bits . 00000000)"
        )
        path.write_text(d8 + "\n", encoding="utf-8")
        result = run_sens(path)
        assert result.returncode == 2
        assert "D8" in result.stdout

    print("SENS compiler-semantic request: REAL PRODUCER OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
